### PR TITLE
Add withdrawFrom function

### PR DESCRIPTION
**Pull request by dmihal**
Had an idea for this function, which basically combines transferFrom and withdraw, hopefully simplifying contracts that use WETH and saving gas (fewer SSTOREs)

Let me know what you think.

### CODE REVIEW

**Review by albertocuestacanada — CHANGES_REQUESTED** [review]
I'm fully in favor of this. I'd even ask you to add a `depositTo(address to, uint amount)` function as well. Unfortunately `depositFrom` won't be possible.

**Comment by Ro5s** [comment]
neat way to simplify send / unwrap for target account.

**Comment by Ro5s** [comment]
Ack (sat on phone) reopened! 😀

**Comment by albertocuestacanada** [comment]
@dmihal, could you please add tests for this?

**Review by Ro5s — COMMENTED** [review]
withdrawFrom() lgtm! for my own continued nitpicks, I conformed the spacing in functions, and made require() statement (block.timestamp v. deadline) match more to OpenZeppelin and dai syntax: https://github.com/OpenZeppelin/openzeppelin-contracts/blob/53516bc555a454862470e7860a9b5254db4d00f5/contracts/token/ERC20/ERC20Permit.sol

**Review by Ro5s — COMMENTED** [review]
adding depositTo() function :+1:

**Comment by Ro5s** [comment]
also adding a `withdrawTo()`. I figure that without `if` statement of `withdrawFrom()`, end users save gas in making direct transfer to another via WETH ~ > ETH.

**Comment by Ro5s** [comment]
for sprint purposes, going to merge to move repo in sync with addition of lean `withdraw` functions and syntax changes. awesome adds every1~ :muscle:

**Pull request merged**
