### PR TITLE
fix: duplicate readings and bump eth-gas-reporter

### LINKED ISSUE #4: Copy to memory instead of reading twice
Lines 45, 74 and 76.

### PR DESCRIPTION
**Pull request by albertocuestacanada**
Removed duplicate readings.

Fixes #4

### CODE REVIEW

**Comment by albertocuestacanada** [comment]
Before:
```
·-----------------------------|---------------------------|---------------|----------------------------·
|     Solc version: 0.7.0     ·  Optimizer enabled: true  ·  Runs: 20000  ·  Block limit: 9500000 gas  │
······························|···························|···············|·····························
|  Methods                                                                                             │
·············|················|·············|·············|···············|··············|··············
|  Contract  ·  Method        ·  Min        ·  Max        ·  Avg          ·  # calls     ·  eur (avg)  │
·············|················|·············|·············|···············|··············|··············
|  WETH10    ·  approve       ·          -  ·          -  ·        43913  ·           2  ·          -  │
·············|················|·············|·············|···············|··············|··············
|  WETH10    ·  deposit       ·          -  ·          -  ·        43938  ·           7  ·          -  │
·············|················|·············|·············|···············|··············|··············
|  WETH10    ·  permit        ·          -  ·          -  ·        71411  ·           1  ·          -  │
·············|················|·············|·············|···············|··············|··············
|  WETH10    ·  transfer      ·          -  ·          -  ·        36379  ·           1  ·          -  │
·············|················|·············|·············|···············|··············|··············
|  WETH10    ·  transferFrom  ·      29871  ·      36845  ·        33358  ·           2  ·          -  │
·············|················|·············|·············|···············|··············|··············
|  WETH10    ·  withdraw      ·          -  ·          -  ·        22582  ·           1  ·          -  │
·············|················|·············|·············|···············|··············|··············
|  Deployments                ·                                           ·  % of limit  ·             │
······························|·············|·············|···············|··············|··············
|  WETH10                     ·          -  ·          -  ·      1191225  ·      12.5 %  ·          -  │
·-----------------------------|-------------|-------------|---------------|--------------|-------------·```

**Comment by albertocuestacanada** [comment]
After: ```
·-----------------------------|---------------------------|---------------|----------------------------·
|     Solc version: 0.7.0     ·  Optimizer enabled: true  ·  Runs: 20000  ·  Block limit: 9500000 gas  │
······························|···························|···············|·····························
|  Methods                                                                                             │
·············|················|·············|·············|···············|··············|··············
|  Contract  ·  Method        ·  Min        ·  Max        ·  Avg          ·  # calls     ·  eur (avg)  │
·············|················|·············|·············|···············|··············|··············
|  WETH10    ·  approve       ·          -  ·          -  ·        43913  ·           2  ·          -  │
·············|················|·············|·············|···············|··············|··············
|  WETH10    ·  deposit       ·          -  ·          -  ·        43938  ·           7  ·          -  │
·············|················|·············|·············|···············|··············|··············
|  WETH10    ·  permit        ·          -  ·          -  ·        71411  ·           1  ·          -  │
·············|················|·············|·············|···············|··············|··············
|  WETH10    ·  transfer      ·          -  ·          -  ·        36379  ·           1  ·          -  │
·············|················|·············|·············|···············|··············|··············
|  WETH10    ·  transferFrom  ·      29392  ·      36819  ·        33106  ·           2  ·          -  │
·············|················|·············|·············|···············|··············|··············
|  WETH10    ·  withdraw      ·          -  ·          -  ·        22582  ·           1  ·          -  │
·············|················|·············|·············|···············|··············|··············
|  Deployments                ·                                           ·  % of limit  ·             │
······························|·············|·············|···············|··············|··············
|  WETH10                     ·          -  ·          -  ·      1168765  ·      12.3 %  ·          -  │
·-----------------------------|-------------|-------------|---------------|--------------|-------------·
```

**Comment by albertocuestacanada** [comment]
Apart from only checking the allowance if `msg.sender != from`, I think that `if (a && b) {}` might have a higher cost than `if (a) { if (b) {}}` because of the `&&` operator.

**Comment by Ro5s** [comment]
lazered! :1234:

**Pull request merged**
