### PR TITLE
Formatting

### PR DESCRIPTION
**Pull request by PaulRBerg**
I ran prettier with the current `.prettierrc` configuration + removed the superfluous indents in the contract.

If any of the current big PRs get merged before this, I'll recreate this branch and reapply the formatting.

### CODE REVIEW

**Comment by albertocuestacanada** [comment]
[PR28](https://github.com/wETH-v2/wETH-v2/pull/28) needs to be merged before we do any large-scale changes, it's huge by now.

**Comment by PaulRBerg** [comment]
Yeah, no worries. I'll wait for that to be merged and re-apply my changes.

**Comment by albertocuestacanada** [comment]
Note I've merged the monster branch, you might want to reimplement this off `main` instead of working through the conflicts.

**Comment by PaulRBerg** [comment]
Closing this in favour of #42.

I deleted my fork of this repo in the meantime.

**Pull request closed without merging**
