### PR TITLE
Fix flash mint, reorder functions and add NatSpec comments

### LINKED ISSUE #26: Natspec is required for all methods

### PR DESCRIPTION
**Pull request by albertocuestacanada**
Segregated Minter and Mintable interfaces.

Reintroduced license spdx tag.

Fixes #26, #27 and #30. This PR morphed into a kind of `dev` branch.

### CODE REVIEW

**Comment by albertocuestacanada** [comment]
I thought about it and removed the `lock` for `deposit*` functions. In `withdraw*` functions it just checks it is unlocked.

It would be possible to `withdraw` and use the callback for `flashMint`, which is fine, is the opposite that would cause an issue.

I'm pretty sure that many contracts are not prepared to deal with huge amounts of Ether. When contracts upgrade or deploy for WETH10, they should be prepared to receive huge amounts of Weth.

**Comment by albertocuestacanada** [comment]
Fixes #30, I think

**Comment by dmihal** [comment]
Any reason locked defaults to 1 instead of 0? Using a variable that's 0 would save gas.

**Comment by dmihal** [comment]
Personally, I prefer using a storage variable to track the outstanding flash loan, instead of the mutex. But I'm open to discussing this.

**Comment by albertocuestacanada** [comment]
@dmihal, how would you use a storage variable to track the outstanding loan instead of the mutex? Would you do a branch with an example?

Personally I'm not that worried with reentrancy on `flashMint`, I think the overflow checks take care of that.

What worries me more, and the reason for the mutex, is that if this contract grows to hold several billion ETH it could be used to break already deployed contracts via `flashMint` and `withdraw`.

Note the difference with `flashMint` on his own, which mints WETH10 and can only be used with contracts deployed after it.

**Comment by albertocuestacanada** [comment]
I'm merging this monster branch, let's work on the details on smaller PRs

**Pull request merged**
